###通用配置###
spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    platform: mysql
    url: jdbc:mysql://${custom.datasource.mysql.host}:${custom.datasource.mysql.port}/${custom.datasource.mysql.database}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Hongkong
    username: ${custom.datasource.mysql.username}
    password: ${custom.datasource.mysql.password}
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml