### 自定义配置 ###
debug: true
server:
  port: 8888
spring:
  profiles:
    ## 环境id，与pom文件中的profiles.profile.id对应 ##
    active: dev
custom:
  datasource:
    mysql:
      ## mysql服务ip ##
      host: xx.xx.xx.xx
      ## mysql服务段偶偶 ##
      port: 3306
      username: root
      password: xxx
      ## 数据库名称 ##
      database: xxx